name: Lint and Test Python

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  lint-and-test:
    defaults:
      run:
        working-directory: lib/py/

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"
        cache-dependency-path: lib/py/requirements.txt

    - name: Set up Python ${{ matrix.python-version }} dependencies
      run: pip install -r requirements.txt

    - name: Lint
      run: |
        make lint

    - name: Test
      run: |
        make test
